# Generated by Django 5.2 on 2025-04-17 09:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Question Text')),
                ('content_type', models.CharField(choices=[('text', 'Text Only'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10)),
                ('question_type', models.CharField(choices=[('single', 'Single Answer'), ('multiple', 'Multiple Answers'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('video', models.FileField(blank=True, null=True, upload_to='question_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg'])])),
                ('correct_answer_text', models.TextField(blank=True, help_text='Correct answer for true_false or fill_blank', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correct_answers', models.ManyToManyField(blank=True, related_name='correct_for_questions', to='questions.option')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'key')},
        ),
    ]
