# Generated by Django 5.2 on 2025-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
