# Chỉ định các giai đoạn (phases) trong quá trình build
[phases.setup]
  # Cài đặt các gói hệ thống cần thiết
  aptPkgs = ['pkg-config', 'libmysqlclient-dev', 'default-libmysqlclient-dev', 'build-essential']

  # Chỉ định phiên bản Python (nếu cần, ví dụ Python 3.10)
  pythonVersion = '3.11'  # Thay đổi nếu bạn muốn dùng phiên bản khác

[phases.build]
  # Lệnh để cài đặt các thư viện Python từ requirements.txt
  cmds = ['pip install -r requirements.txt']

[phases.start]
  # Lệnh để chạy ứng dụng Django
  cmds = ['python manage.py migrate', 'gunicorn linux_test_system.wsgi:application --bind 0.0.0.0:$PORT']

# Cấu hình biến môi trường
[environment]
  # Nếu cần thiết, thêm các biến môi trường cho mysqlclient
  MYSQLCLIENT_CFLAGS = '-I/usr/include/mysql'
  MYSQLCLIENT_LDFLAGS = '-L/usr/lib/x86_64-linux-gnu -lmysqlclient'