# Generated by Django 5.2 on 2025-04-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='Không có mô tả', null=True)),
                ('date', models.DateField(default='2025-01-01', help_text='Ngày thi')),
                ('duration', models.IntegerField(default=60, help_text='Thời gian thi (phút)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(to='questions.question')),
            ],
        ),
    ]
