# Generated by Django 5.1.4 on 2025-03-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(default='2025-01-01', help_text='Ngày thi'),
        ),
    ]
